language: java
dist: trusty
sudo: required

before_install:
  - sudo apt-get install -y fonts-noto

jobs:
  include:
    - stage: prepare
      script: ./gradlew clean wrapper resolveDependencies
    - stage: test
      script: ./gradlew test --full-stacktrace
    - stage: build
      script: ./gradlew build
    - stage: build image
      script: ./gradlew buildDocker

env:
  global:
    - GRADLE_OPTS="-Xms128m -Xmx1g"

jdk:
  - oraclejdk8

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)
