language: java
dist: trusty
#sudo: required

before_install:
  - sudo apt-get install -y fonts-noto

script: ./gradlew buildDocker

env:
  global:
    - GRADLE_OPTS="-Xms128m -Xmx1g"

jdk:
  - oraclejdk8

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

after_success:
  - bash <(curl -s https://codecov.io/bash)
